name = "minifig-hub"
compatibility_date = "2024-09-23"
main = "src/worker.ts"

# Configure the assets directory
[assets]
directory = "./www"
binding = "ASSETS"

# Map the custom domain
[[routes]]
pattern = "minifig-hub.com/*"
zone_name = "minifig-hub.com"

[[routes]]
pattern = "www.minifig-hub.com/*"
zone_name = "minifig-hub.com"