
import { Minifigure, Theme, CharacterCollection } from '../types';

export const MOCK_MINIFIGS: Minifigure[] = [
  {
    item_no: 'sw0001a',
    name: 'Battle Droid Tan with Tan Torso',
    theme_name: 'Star Wars',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0001a.png',
    category_id: 1,
    year_released: 1999,
    owned: true,
  },
  {
    item_no: 'sw1074',
    name: 'The Mandalorian (Din Djarin / Beskar Armor)',
    theme_name: 'Star Wars',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw1074.png',
    category_id: 1,
    year_released: 2020,
    owned: false,
  },
  {
    item_no: 'sh633',
    name: 'Iron Man with Silver Hexagon on Chest',
    theme_name: 'Super Heroes',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh633.png',
    category_id: 2,
    year_released: 2020,
    owned: true,
  },
  {
    item_no: 'hp143',
    name: 'Harry Potter, Dark Blue Open Jacket',
    theme_name: 'Harry Potter',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/hp143.png',
    category_id: 3,
    year_released: 2018,
    owned: true,
  },
  {
    item_no: 'sw0021',
    name: 'Luke Skywalker (Tatooine)',
    theme_name: 'Star Wars',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0021.png',
    category_id: 1,
    year_released: 1999,
    owned: false,
  },
  {
    item_no: 'sh0038',
    name: 'Spider-Man - Black Web Pattern',
    theme_name: 'Super Heroes',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0038.png',
    category_id: 2,
    year_released: 2012,
    owned: false,
  },
  {
    item_no: 'sh0002',
    name: 'Batman - Black Suit with Yellow Belt',
    theme_name: 'Super Heroes',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0002.png',
    category_id: 2,
    year_released: 2012,
    owned: true,
  },
  {
    item_no: 'sw0004',
    name: 'Darth Vader (Gray Head)',
    theme_name: 'Star Wars',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0004.png',
    category_id: 1,
    year_released: 1999,
    owned: false,
  },
  {
    item_no: 'njo001',
    name: 'Kai - Ninja',
    theme_name: 'Ninjago',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/njo001.png',
    category_id: 4,
    year_released: 2011,
    owned: true,
  },
  {
    item_no: 'adv001',
    name: 'Johnny Thunder',
    theme_name: 'Adventurers',
    image_url: 'https://img.bricklink.com/ItemImage/MN/0/adv001.png',
    category_id: 5,
    year_released: 1998,
    owned: false,
  },
];

export const MOCK_THEMES: Theme[] = [
  { id: '1', name: 'Star Wars', minifig_count: 1545, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0004.png' },
  { id: '2', name: 'Super Heroes', minifig_count: 1118, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0002.png' },
  { id: '3', name: 'Harry Potter', minifig_count: 654, image_url: 'https://img.bricklink.com/ItemImage/MN/0/hp001.png' },
  { id: '4', name: 'Ninjago', minifig_count: 914, image_url: 'https://img.bricklink.com/ItemImage/MN/0/njo001.png' },
  { id: '5', name: 'Friends', minifig_count: 864, image_url: 'https://img.bricklink.com/ItemImage/MN/0/frnd001.png' },
  { id: '6', name: 'Collectible Minifigures', minifig_count: 810, image_url: 'https://img.bricklink.com/ItemImage/MN/0/col001.png' },
];

export const MOCK_CHARACTERS: CharacterCollection[] = [
  { id: 'c1', name: 'Luke Skywalker', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0021.png' },
  { id: 'c2', name: 'Batman', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0002.png' },
  { id: 'c3', name: 'Darth Vader', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0004.png' },
  { id: 'c4', name: 'Spider-Man', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0038.png' },
  { id: 'c5', name: 'Iron Man', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0036.png' },
  { id: 'c6', name: 'Yoda', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0051.png' },
  { id: 'c7', name: 'Harry Potter', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/hp001.png' },
  { id: 'c8', name: 'Boba Fett', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0002.png' },
  { id: 'c9', name: 'Stormtrooper', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sw0188.png' },
  { id: 'c10', name: 'Captain America', minifig_count: 0, image_url: 'https://img.bricklink.com/ItemImage/MN/0/sh0031.png' },
];
